version: '2.1'

services:
  100corretor:
    image: 100corretor
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect ./bin/www